receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317 #default
      http:
        endpoint: 0.0.0.0:4318 #default
        cors:
          allowed_origins:
            - http://localhost:3012

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  resource:
    attributes:

extensions:
  health_check:

exporters:
  prometheus:
    endpoint: collector:6666
    # namespace: default
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - prometheus
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp
  extensions: [health_check]

  telemetry:
    logs:
      level: debug
    metrics:
      address: 0.0.0.0:8888
